# Generated by Django 2.0.6 on 2018-06-25 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawing', '0002_auto_20180618_1945'),
        ('filterbank', '0002_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='representation_images')),
            ],
        ),
        migrations.CreateModel(
            name='DiCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='representation_dicoms')),
            ],
        ),
        migrations.CreateModel(
            name='NpArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='h5files')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='virtualrepresentation',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='parsingrequest',
            name='virtualrep',
        ),
        migrations.AddField(
            model_name='filter',
            name='channel',
            field=models.CharField(default='maxisp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='inputvid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='outputvid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='returnchannel',
            field=models.CharField(default='nana', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='settings',
            field=models.CharField(default='ons', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representation',
            name='vid',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='VirtualRepresentation',
        ),
        migrations.AddField(
            model_name='representation',
            name='dicom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.DiCom'),
        ),
        migrations.AddField(
            model_name='representation',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.AImage'),
        ),
        migrations.AddField(
            model_name='representation',
            name='nparray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.NpArray'),
        ),
    ]
