# Generated by Django 2.0.6 on 2018-06-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0003_auto_20180625_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nparray',
            name='file',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='representation',
            name='dicom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.DiCom'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.AImage'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='nparray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filterbank.NpArray'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='vid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
