# Generated by Django 2.0.6 on 2018-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0004_auto_20180626_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='representation_images'),
        ),
    ]
