# Generated by Django 2.0.6 on 2018-06-29 17:00

from django.db import migrations, models
import filterbank.models


class Migration(migrations.Migration):

    dependencies = [
        ('filterbank', '0005_auto_20180627_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=filterbank.models.OverwriteStorage(), upload_to='representation_images'),
        ),
    ]
