version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: python3.6 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
  worker:
    build: .
    command: python3.6 manage.py runworker channels maxisp bioconverter niftioutflower imageoutflower
    volumes:
      - .:/code
    links:
      - redis
  notebook:
    image: aichat_web:latest
    command: python3.6 manage.py shell_plus --notebook
    volumes:
      - .:/code
    ports:
      - "8890:8888"