# Generated by Django 2.0.6 on 2018-07-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bioimagefiles', verbose_name='bioimage')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.CharField(max_length=1000)),
                ('inputid', models.IntegerField()),
                ('outputvid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('inputtype', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=100)),
                ('defaultsettings', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='converter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioconverter.Converter'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
