# Generated by Django 2.0.7 on 2018-07-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_auto_20180704_1616'),
        ('biouploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioimage',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawing.Sample'),
        ),
    ]
